- name: Ensure lifecycle policy is set
  gm_ecs_ecr:
    region: "{{ aws_ecr_push_region }}"
    name: "{{ item }}"
    lifecycle_policy: "{{ aws_ecr_push_post_lifecycle_policy }}"
  loop: "{{ aws_ecr_push_image }}"
