dependencies:
- role: aws-ecr-push
  aws_ecr_push_tag:
    - build_{{ zuul.build }}
    - pipeline_{{ zuul.pipeline }}
    - "{%- if zuul.newrev is defined %}newrev_{{ zuul.newrev }}{%- else -%}change_{{ zuul.project.short_name }}_{{ zuul.change }}{%- endif -%}"
